int DayNumber = 9;
string Day = "Понедельник";
if (DayNumber < 1 || DayNumber > 7) Day = "Ошибка ввода";
if (DayNumber == 2) Day = "Вторник";
if (DayNumber == 3) Day = "Среда";
if (DayNumber == 4) Day = "Четверг";
if (DayNumber == 5) Day = "Пятница";
if (DayNumber == 6) Day = "Суббота";
if (DayNumber == 7) Day = "Воскресенье";
Console.WriteLine (Day);